name: ZXCalculusForCAP
version: "2023.07-02"
license: "GPL-2.0-or-later"
date: 2023-07-06
description: |
    The category of ZX-diagrams

authors:
    - name: Fabian Zickgraf
      url: https://zickgraf.github.io/

maintainers:
    - name: Fabian Zickgraf
      url: https://zickgraf.github.io/

GAP: ">= 4.12.1"

needed-pkgs:
    - name: "CAP"
      version: ">= 2023.07-02"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "MonoidalCategories"
      version: ">= 2023.05-03"
      url: "https://homalg-project.github.io/pkg/MonoidalCategories"
    - name: "FinSetsForCAP"
      version: ">= 2023.06-05"
      url: "https://homalg-project.github.io/pkg/FinSetsForCAP"

suggested-pkgs:
    - name: "FunctorCategories"
      version: ">= 2023.07-01"
      url: "https://homalg-project.github.io/pkg/FunctorCategories"

www: https://homalg-project.github.io/pkg/ZXCalculusForCAP
readme: README.md
packageinfo: https://homalg-project.github.io/ZXCalculusForCAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/ZXCalculusForCAP/releases/download/v2023.07-02/ZXCalculusForCAP-2023.07-02.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/ZXCalculusForCAP/releases/download/v2023.07-02/ZXCalculusForCAP-2023.07-02.zip

pdf: https://github.com/homalg-project/ZXCalculusForCAP/releases/download/v2023.07-02/ZXCalculusForCAP-2023.07-02-manual.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Zic06</span>]   <b class='BibAuthor'>Zickgraf, F.</b>,
     <i class='BibTitle'>ZXCalculusForCAP, The category of ZX-diagrams,
             Version 2023.07-02</i>
     (<span class='BibYear'>7-06</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/ZXCalculusForCAP">https://homalg-project.github.io/pkg/ZXCalculusForCAP</a></span>.
    </p>
    

bibtex: |
    @misc{ ZXCalculusForCAP2023.07-02,
      author =           {Zickgraf, F.},
      title =            {{ZXCalculusForCAP},   The   category  of  ZX-diagrams,
                          {V}ersion 2023.07-02},
      month =            {3-},
      year =             {7-06},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/ZXCalculusForCAP}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{ZXCalculusForCAP}}},
      printedkey =       {Zic06}
    }

