name: ZXCalculusForCAP
version: "2024.06-02"
license: "GPL-2.0-or-later"
date: 2024-06-27
description: |
    The category of ZX-diagrams

authors:
    - name: Fabian Zickgraf
      url: https://zickgraf.github.io/

maintainers:
    - name: Fabian Zickgraf
      url: https://zickgraf.github.io/

GAP: ">= 4.12.1"

needed-pkgs:
    - name: "CAP"
      version: ">= 2023.08-18"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "MonoidalCategories"
      version: ">= 2023.05-03"
      url: "https://homalg-project.github.io/pkg/MonoidalCategories"
    - name: "FinSetsForCAP"
      version: ">= 2023.06-05"
      url: "https://homalg-project.github.io/pkg/FinSetsForCAP"

suggested-pkgs:
    - name: "FunctorCategories"
      version: ">= 2023.07-01"
      url: "https://homalg-project.github.io/pkg/FunctorCategories"
    - name: "json"
      version: "2.1.1"
      url: "https://gap-packages.github.io/json/"

www: https://homalg-project.github.io/pkg/ZXCalculusForCAP
readme: README.md
packageinfo: https://homalg-project.github.io/ZXCalculusForCAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/ZXCalculusForCAP/releases/download/v2024.06-02/ZXCalculusForCAP-2024.06-02.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/ZXCalculusForCAP/releases/download/v2024.06-02/ZXCalculusForCAP-2024.06-02.zip

pdf: https://github.com/homalg-project/ZXCalculusForCAP/releases/download/v2024.06-02/ZXCalculusForCAP-2024.06-02-manual.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Zic27</span>]   <b class='BibAuthor'>Zickgraf, F.</b>,
     <i class='BibTitle'>ZXCalculusForCAP, The category of ZX-diagrams,
             Version 2024.06-02</i>
     (<span class='BibYear'>6-27</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/ZXCalculusForCAP">https://homalg-project.github.io/pkg/ZXCalculusForCAP</a></span>.
    </p>
    

bibtex: |
    @misc{ ZXCalculusForCAP,
      author =           {Zickgraf, F.},
      title =            {{ZXCalculusForCAP},        The       category       of
                          ZX\texttt{\symbol{45}}diagrams,              {V}ersion
                          2024.06\texttt{\symbol{45}}02},
      month =            {4\texttt{\symbol{45}}},
      year =             {6\texttt{\symbol{45}}27},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/ZXCalculusForCAP}
                          {\texttt{https://homalg\texttt{\symbol{45}}project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{ZXCalculusForCAP}}},
      printedkey =       {Zic27}
    }

