name: ZXCalculusForCAP
version: "2025.08-03"
license: "GPL-2.0-or-later"
date: 2025-08-24
description: |
    The category of ZX-diagrams

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Fabian Zickgraf
      url: https://zickgraf.github.io/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

GAP: ">= 4.13.0"

needed-pkgs:
    - name: "CAP"
      version: ">= 2025.06-06"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "MonoidalCategories"
      version: ">= 2023.05-03"
      url: "https://homalg-project.github.io/pkg/MonoidalCategories"
    - name: "FinSetsForCAP"
      version: ">= 2023.06-05"
      url: "https://homalg-project.github.io/pkg/FinSetsForCAP"

suggested-pkgs:
    - name: "FunctorCategories"
      version: ">= 2023.07-01"
      url: "https://homalg-project.github.io/pkg/FunctorCategories"
    - name: "json"
      version: "2.1.1"
      url: "https://gap-packages.github.io/json/"

www: https://homalg-project.github.io/pkg/ZXCalculusForCAP
readme: README.md
packageinfo: https://homalg-project.github.io/ZXCalculusForCAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/ZXCalculusForCAP/releases/download/v2025.08-03/ZXCalculusForCAP-2025.08-03.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/ZXCalculusForCAP/releases/download/v2025.08-03/ZXCalculusForCAP-2025.08-03.zip

pdf: https://github.com/homalg-project/ZXCalculusForCAP/releases/download/v2025.08-03/ZXCalculusForCAP-2025.08-03-manual.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BZ24</span>]   <b class='BibAuthor'>Barakat, M. and Zickgraf, F.</b>,
     <i class='BibTitle'>ZXCalculusForCAP, The category of ZX-diagrams,
             Version 2025.08-03</i>
     (<span class='BibYear'>8-24</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/ZXCalculusForCAP">https://homalg-project.github.io/pkg/ZXCalculusForCAP</a></span>.
    </p>
    

bibtex: |
    @misc{ ZXCalculusForCAP,
      author =           {Barakat, M. and Zickgraf, F.},
      title =            {{ZXCalculusForCAP},       {The       category       of
                          ZX\texttt{\symbol{45}}diagrams},             {V}ersion
                          2025.08\texttt{\symbol{45}}03},
      month =            {5\texttt{\symbol{45}}},
      year =             {8\texttt{\symbol{45}}24},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/ZXCalculusForCAP}
                          {\texttt{https://homalg\texttt{\symbol{45}}project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{ZXCalculusForCAP}}},
      printedkey =       {BZ24}
    }

